---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{R global_options}

knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```

## Loading and preprocessing the data

First set the necessary libraries and load a function to output summary in a formatted form
.
```{R message=FALSE}
library(data.table)
library(stringr)
library(plyr)
library(dplyr)
library(lattice)

source("SummaryOut.R")

```

The data are available as zip file. This file contains one csv file named activity.csv. It is already unpacked into the subfolder "figure" under the folder the script resides in.

The data file is a standard csv file with the following properties:

* the first row contains the column names
* column separator is ,
* String delimiter is "
* missing values are marked as NA

```{R}
f <- ".\\figure\\activity.csv"
rawData <- fread(f, sep = ",")
rawData$date <- as.Date(rawData$date)
summary.out(rawData)
```

## What is mean total number of steps taken per day?

To answer this questions the raw data are summed up on date level. 

```{R}
perDay <- rawData %>% select(date, steps) %>% 
                      filter(!is.na(steps)) %>% 
                      ddply(.(date), summarise, total.steps.per.day = sum(steps))
summary.out(perDay)
```

The aggregated data are presented as histogram.

```{R}
hist(perDay$total.steps.per.day[!is.na(perDay$total.steps.per.day)], 
      breaks = 20,
      main = "Total Steps per Day",
      xlab = "Steps per Day",
      ylab = "Found on n Days",
      col = "red") 
```

```{R}
mean.total.steps <- mean(perDay$total.steps.per.day)
print(paste("Mean of total steps:", as.character(round(mean.total.steps, digits = 0))))
median.total.steps <- median(perDay$total.steps.per.day)
print(paste("Median of total steps:", round(mean.total.steps, digits = 0)))
```

## What is the average daily activity pattern?

To answer this question, the raw data are aggregated on interval level. The average is calculated. Rows containing NA values in step column are removed.

```{R}
avg.daily.act.pat <- rawData %>% select(interval, steps) %>% 
                      filter(!is.na(steps)) %>%
                      ddply(.(interval), summarize, average.steps.per.interval = mean(steps))
summary.out(avg.daily.act.pat)
```

The intervall is taken in 5 minutes steps. When the full hour is reached, the hour is included and the minutes is set back to 0 (i.e. 50, 55, 100, 105 or 1250, 1255, 1300). Start value is 00. The last step of the day is 2355.

To increase readabillity the interval is converted to time format. To gain this, the value is interpreted as string and concatenated with preceeding 0000. Now the rightmost 4 characters of this string are taken and converted to posix date/time. The date part can be ignorred. 

```{R}
avg.daily.act.pat$interval_dat <- 
  strptime(str_sub(paste0("0000", avg.daily.act.pat$interval), -4, -1), "%H%M")
str(avg.daily.act.pat)
```

Now the the data are visualized as line graph.

```{R}
with(avg.daily.act.pat, 
      plot(interval_dat, average.steps.per.interval,
                type = "l",
                main = "Daily activity pattern (missing values excluded)",
                xlab = "Time of Day",
                ylab = "Average Steps per Intervall"))
```

To find the time interval having the maximum number of steps, max is calculated and than the interval is selected from the data.

```{R}
  max.steps <- max(avg.daily.act.pat$average.steps.per.interval)
  paste("The maximum number of average steps/interval is", round(max.steps, digits = 0), 
        "it occured at", format(avg.daily.act.pat$interval_dat[avg.daily.act.pat$average.steps.per.interval == max.steps], "%H:%M"))
```


## Imputing missing values

To fill the missing values the average value of the corresponding intervall is used.The average is already calculated. Now these averages are bound to the raw data. Afterwards the missing steps are filled from the average steps and a new set with just date, interval and steps is derived from the data.

```{R}

t <- merge.data.frame(
        rawData, avg.daily.act.pat, 
                  by.x = "interval", 
                  by.y = "interval")

t$steps[is.na(t$steps)] <- t$average.steps.per.interval[is.na(t$steps)]
enhanced.set <- t %>% select(interval, steps, date)
summary.out(enhanced.set)
```

The cleaned up data are now summoned up by date.

```{R}
enhanced.perDay <- 
  enhanced.set %>% select(date, steps) %>% 
                   ddply(.(date), summarise, total.steps.per.day = sum(steps))
summary.out(enhanced.perDay)
```

From these data a histogram is generated.

```{R}
hist(enhanced.perDay$total.steps.per.day[!is.na(enhanced.perDay$total.steps.per.day)], 
      breaks = 20,
      main = "Total Steps per Day",
      xlab = "Steps per Day",
      ylab = "Found on n Days",
      col = "red") 
```

```{R}
enhanced.mean.total.steps <- mean(enhanced.perDay$total.steps.per.day)
print(paste("Mean of total steps:", as.character(round(enhanced.mean.total.steps, digits = 0))))
enhanced.median.total.steps <- median(enhanced.perDay$total.steps.per.day)
print(paste("Median of total steps:", round(enhanced.mean.total.steps, digits = 0)))
```

## Are there differences in activity patterns between weekdays and weekends?

To the data set, that received average number of steps to fill missing values, a collumn is added to hold the weekday property. The type of the weekday is determined by the first character of the weekday name. The two weekend's days start wit with an "S" (Saturday and Sunday). The classification is converted to a factor value.

```{R}
t <- Sys.setlocale(category = "LC_ALL", locale = "English")
enhanced.set$weekday <- 
  factor(
    ifelse(substr(weekdays(enhanced.set$date), 1, 1) == "S", "weekend", "weekday"))
```

Next the data are grouped by weekday characteristic and interval. The average of steps for this grouping is calculated.

```{R}
weekday.set <- enhanced.set %>% 
               select(weekday, interval, steps) %>%
               ddply(.(weekday, interval), summarize, 
                    average.steps.per.interval = mean(steps))
summary.out(weekday.set)
```

The data are sorted by weekday characteristic and interval. From the data two line graphs, one for weekends, one for weedays, are generated.

```{R}
weekday.set <- weekday.set %>% arrange(weekday, interval)

xyplot(average.steps.per.interval ~ interval | weekday, data = weekday.set, layout = c(1,2), type = "l", ylab = "Number of steps", xlab = "Intervall")
```