---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

First set the necessary libraries and define a function.
```{R message=FALSE}
library(data.table)
library(stringr)
library(plyr)
library(dplyr)

summary.out <- function(x) {
  t <- as.data.frame(summary(x))
  names(t) <- c("Empty", "Column", "Value")
  t[!is.na(t$Value),2:3]
}
```

The data are available as zip file. This file contains one csv file named activity.csv. It is unpacked into the subfolder .\figure.

The data file is a standard csv file with the following properties:

* the first row contains the column names
* column separator is ,
* String delimiter is "
* missing values are marked as NA

```{R}
f <- ".\\figure\\activity.csv"
rawData <- fread(f, sep = ",")
rawData$date <- as.Date(rawData$date)
summary.out(rawData)
```

## What is mean total number of steps taken per day?

To answer this questions the raw data are aggregated on date level. 

```{R}
perDay <- rawData %>% select(date, steps) %>% 
                      filter(!is.na(steps)) %>% 
                      ddply(.(date), summarise, total.steps.per.day = sum(steps))
summary.out(perDay)
```

```{R}
hist(perDay$total.steps.per.day[!is.na(perDay$total.steps.per.day)], 
      breaks = 20,
      main = "Total Steps per Day",
      xlab = "Steps per Day",
      ylab = "Found on n Days",
      col = "red") 
```

```{R}
mean.total.steps <- mean(perDay$total.steps.per.day)
print(paste("Mean of total steps:", as.character(round(mean.total.steps, digits = 0))))
median.total.steps <- median(perDay$total.steps.per.day)
print(paste("Median of total steps:", round(mean.total.steps, digits = 0)))
```

## What is the average daily activity pattern?

```{R}
avg.daily.act.pat <- rawData %>% select(interval, steps) %>% 
                      filter(!is.na(steps)) %>%
                      ddply(.(interval), summarize, average.steps.per.interval = mean(steps))
summary.out(avg.daily.act.pat)
```

The intervall is taken in 5 minutes steps. When then full hour is reached the hour is included and the minutes is set back to 0 (i.e. 50, 55, 100, 105 or 1250, 1255, 1300). Start value is 00. The last step of the day is 2355.

To increase radeballity the interval is converted to time format.

```{R}
avg.daily.act.pat$interval_dat <- 
  strptime(str_sub(paste0("0000", avg.daily.act.pat$interval), -4, -1), "%H%M")
head(avg.daily.act.pat)
```

Now the the data are visualized:

```{R}
with(avg.daily.act.pat, plot(interval_dat, average.steps.per.interval,
                             type = "l",
                             main = "Daily activity pattern (missing values excluded)",
                             xlab = "Time of Day",
                             ylab = "Average Steps per Intervall"))
```

## Imputing missing values
To fill the missing values the average value of the corresponding intervall is used.

The average is already calculated. Now these avergaes are bound to the data.
```{R}

t <- merge.data.frame(rawData, avg.daily.act.pat, by.x = "interval", by.y = "interval")
t$steps[is.na(t$steps)] <- t$average.steps.per.interval[is.na(t$steps)]
enhanced.set <- t %>% select(interval, steps, date)
summary.out(enhanced.set)
```

Now to step 1 corresponding data are build and presented

```{R}
enhanced.perDay <- enhanced.set %>% select(date, steps) %>% 
                                    ddply(.(date), summarise, total.steps.per.day = sum(steps))
summary.out(enhanced.perDay)
```

```{R}
hist(enhanced.perDay$total.steps.per.day[!is.na(enhanced.perDay$total.steps.per.day)], 
      breaks = 20,
      main = "Total Steps per Day",
      xlab = "Steps per Day",
      ylab = "Found on n Days",
      col = "red") 
```

```{R}
enhanced.mean.total.steps <- mean(enhanced.perDay$total.steps.per.day)
print(paste("Mean of total steps:", as.character(round(enhanced.mean.total.steps, digits = 0))))
enhanced.median.total.steps <- median(enhanced.perDay$total.steps.per.day)
print(paste("Median of total steps:", round(enhanced.mean.total.steps, digits = 0)))
```

## Are there differences in activity patterns between weekdays and weekends?

First to the enhanced data set a column to mark weekdays is added.
```{R}
t <- Sys.setlocale(category = "LC_ALL", locale = "English")
enhanced.set$weekday <- 
  factor(
    ifelse(substr(weekdays(enhanced.set$date), 1, 1) == "S", "weekend", "weekday"))
```
Now group the data by weekday / none-weekday and add again the column with the time value for the interval.
```{R}
weekday.set <- enhanced.set %>% select(weekday, interval, steps) %>%
                                ddply(.(weekday, interval), summarize, 
                                      average.steps.per.interval = mean(steps))
weekday.set$interval_dat <- 
  strptime(str_sub(paste0("0000", weekday.set$interval), -4, -1), "%H%M")
summary.out(weekday.set)
```